queue_rules:
  - name: duplicated default from Automatic merge on approval
    queue_conditions:
      - "#approved-reviews-by>=1"
    merge_conditions:
      - check-success=test (8, 2.13.7)
      - check-success=test (11, 2.13.7)
      - check-success=testPY (11, 2.13.7, 3.5)
      - check-success=testJS (11, 2.13.7)
      - check-success=testWithCoverageReport (8)
      - check-success=buildWithGraal (2.13.7)
    merge_method: merge
  - name: duplicated default from merge scala-steward's PRs
    queue_conditions:
      - author=scala-steward
      - check-success=test (8, 2.13.7)
      - check-success=test (11, 2.13.7)
      - check-success=testPY (11, 2.13.7, 3.5)
      - check-success=testJS (11, 2.13.7)
      - check-success=testWithCoverageReport (8)
      - check-success=buildWithGraal (2.13.7)
    merge_conditions:
      - check-success=test (8, 2.13.7)
      - check-success=test (11, 2.13.7)
      - check-success=testPY (11, 2.13.7, 3.5)
      - check-success=testJS (11, 2.13.7)
      - check-success=testWithCoverageReport (8)
      - check-success=buildWithGraal (2.13.7)
    merge_method: squash

pull_request_rules:
  - name: Automatic merge on approval + merge scala-steward's PRs
    conditions: []
    actions:
      queue:
