#!/bin/bash

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
# make sure to run sbt cli/assembly first
java -jar $SCRIPT_DIR/cli/target/scala-3.5.2/bosatsu-cli-assembly-0.0.7.jar "$@"
