codecov:
  branch: main
  require_ci_to_pass: false
  notify:
    wait_for_ci: false

coverage:
  status:
    project:
      default:
        target: auto
        # scalacheck tests can fluctuate up and down in coverage
        threshold: 2%
    patch:
      default:
        target: auto
        # scalacheck tests can fluctuate up and down in coverage
        threshold: 2%
