workspace(name = "test_workspace")

local_repository(name = "org_bykn_bosatsu",
                 path = "../")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
git_repository(
    name = "io_bazel_rules_scala",
    remote = "git://github.com/bazelbuild/rules_scala",
    commit = "14d9742496859faaf860b1adfc8126f3ed077921" # update this as needed
)
load("@io_bazel_rules_scala//scala:scala.bzl", "scala_repositories")
scala_repositories()

load("@org_bykn_bosatsu//3rdparty:workspace.bzl", "maven_dependencies")

maven_dependencies()
