workspace(name = "test_workspace")

local_repository(name = "org_bykn_bosatsu",
                 path = "../")

git_repository(
    name = "io_bazel_rules_scala",
    remote = "git://github.com/bazelbuild/rules_scala",
    commit = "388a2585f45dff804d006b0e81e1b1a1c60578bc" # update this as needed
)
load("@io_bazel_rules_scala//scala:scala.bzl", "scala_repositories")
scala_repositories()

load("@org_bykn_bosatsu//3rdparty:workspace.bzl", "maven_dependencies")

maven_dependencies()
