// Import runtime
// require("./../_runtime.js") or import from "./../_runtime.js"

const main = ((_a0, _a1, _a2) => [_a0,
  _a1,
  _a2])(BazelDepsApi$default_options_with_scala, BazelDepsApi$merge_dep_List(Bosatsu_Predef$concat(Bosatsu_Predef$map_List(((_a0, _a1) => [1,
          _a0,
          _a1])(((_a0, _a1, _a2) => [_a0,
            _a1,
            _a2])(_js_to_bosatsu_string("com.lihaoyi"), _js_to_bosatsu_string("sourcecode"), _js_to_bosatsu_string("0.1.4")), ((_a0, _a1) => [1,
            _a0,
            _a1])(((_a0, _a1, _a2) => [_a0,
              _a1,
              _a2])(_js_to_bosatsu_string("com.monovore"), _js_to_bosatsu_string("decline"), _js_to_bosatsu_string("1.0.0")), ((_a0, _a1) => [1,
              _a0,
              _a1])(((_a0, _a1, _a2) => [_a0,
                _a1,
                _a2])(_js_to_bosatsu_string("org.bykn"), _js_to_bosatsu_string("fastparse-cats-core"), _js_to_bosatsu_string("0.1.0")), ((_a0, _a1) => [1,
                _a0,
                _a1])(((_a0, _a1, _a2) => [_a0,
                  _a1,
                  _a2])(_js_to_bosatsu_string("org.scala-lang.modules"), _js_to_bosatsu_string("scala-xml"), _js_to_bosatsu_string("1.0.6")), ((_a0, _a1) => [1,
                  _a0,
                  _a1])(((_a0, _a1, _a2) => [_a0,
                    _a1,
                    _a2])(_js_to_bosatsu_string("org.scalacheck"), _js_to_bosatsu_string("scalacheck"), _js_to_bosatsu_string("1.13.5")), ((_a0, _a1) => [1,
                    _a0,
                    _a1])(((_a0, _a1, _a2) => [_a0,
                      _a1,
                      _a2])(_js_to_bosatsu_string("org.scalactic"), _js_to_bosatsu_string("scalactic"), _js_to_bosatsu_string("3.0.1")), ((_a0, _a1) => [1,
                      _a0,
                      _a1])(((_a0, _a1, _a2) => [_a0,
                        _a1,
                        _a2])(_js_to_bosatsu_string("org.spire-math"), _js_to_bosatsu_string("kind-projector"), _js_to_bosatsu_string("0.9.4")), ((_a0, _a1) => [1,
                        _a0,
                        _a1])(((_a0, _a1, _a2) => [_a0,
                          _a1,
                          _a2])(_js_to_bosatsu_string("org.typelevel"), _js_to_bosatsu_string("alleycats-core"), _js_to_bosatsu_string("2.0.0")), ((_a0, _a1) => [1,
                          _a0,
                          _a1])(((_a0, _a1, _a2) => [_a0,
                            _a1,
                            _a2])(_js_to_bosatsu_string("org.typelevel"), _js_to_bosatsu_string("cats-effect"), _js_to_bosatsu_string("2.0.0")), ((_a0, _a1) => [1,
                            _a0,
                            _a1])(((_a0, _a1, _a2) => [_a0,
                              _a1,
                              _a2])(_js_to_bosatsu_string("org.typelevel"), _js_to_bosatsu_string("paiges-core"), _js_to_bosatsu_string("0.3.0")), [0])))))))))), b => (() => {
          const o = b[0];
          return (() => {
            const a = b[1];
            return (() => {
              const v = b[2];
              return BazelDepsApi$scala_dep(o, a, v);
            })();
          })();
        })()), ((_a0, _a1) => [1,
        _a0,
        _a1])(BazelDepsApi$scala_dep_modules(_js_to_bosatsu_string("org.scalatest"), _js_to_bosatsu_string("scalatest"), ((_a0, _a1) => [1,
            _a0,
            _a1])(_js_to_bosatsu_string(""), [0]), _js_to_bosatsu_string("3.0.1"), ((_a0, _a1) => [1,
            _a0,
            _a1])(_js_to_bosatsu_string("org.scalactic:scalactic"), [0])), ((_a0, _a1) => [1,
          _a0,
          _a1])(BazelDepsApi$scala_dep_modules(_js_to_bosatsu_string("org.typelevel"), _js_to_bosatsu_string("cats"), ((_a0, _a1) => [1,
              _a0,
              _a1])(_js_to_bosatsu_string("core"), ((_a0, _a1) => [1,
                _a0,
                _a1])(_js_to_bosatsu_string("free"), ((_a0, _a1) => [1,
                  _a0,
                  _a1])(_js_to_bosatsu_string("kernel"), ((_a0, _a1) => [1,
                    _a0,
                    _a1])(_js_to_bosatsu_string("macros"), [0])))), _js_to_bosatsu_string("2.0.0"), [0]), ((_a0, _a1) => [1,
            _a0,
            _a1])(BazelDepsApi$scala_dep_modules(_js_to_bosatsu_string("com.lihaoyi"), _js_to_bosatsu_string("fastparse"), ((_a0, _a1) => [1,
                _a0,
                _a1])(_js_to_bosatsu_string(""), ((_a0, _a1) => [1,
                  _a0,
                  _a1])(_js_to_bosatsu_string("utils"), [0])), _js_to_bosatsu_string("1.0.0"), ((_a0, _a1) => [1,
                _a0,
                _a1])(_js_to_bosatsu_string("com.lihaoyi:sourcecode"), [0])), [0]))))), BazelDepsApi$standard_scala_replacements);
export {main};