FLAGS = -flto -O3
//FLAGS = -g

all: bosatsu_runtime.o test_out bosatsu_ext_Bosatsu_l_Predef.o bosatsu_ext_Bosatsu_l_Prog.o

bosatsu_runtime.o: bosatsu_runtime.h bosatsu_runtime.c bosatsu_decls_generated.h bosatsu_generated.h
	gcc $(FLAGS) -c -Wall -Werror bosatsu_runtime.c

bosatsu_ext_Bosatsu_l_Predef.o: bosatsu_ext_Bosatsu_l_Predef.c bosatsu_runtime.o
	gcc $(FLAGS) -Wall -Werror -c bosatsu_ext_Bosatsu_l_Predef.c

bosatsu_ext_Bosatsu_l_Prog.o: bosatsu_ext_Bosatsu_l_Prog.c bosatsu_runtime.o
	gcc $(FLAGS) -Wall -Werror -c bosatsu_ext_Bosatsu_l_Prog.c

test_exe: output.c bosatsu_runtime.o bosatsu_ext_Bosatsu_l_Prog.o bosatsu_ext_Bosatsu_l_Predef.o
	gcc $(FLAGS) -o test_exe output.c bosatsu_runtime.o bosatsu_ext_Bosatsu_l_Prog.o bosatsu_ext_Bosatsu_l_Predef.o

test_out: test_exe
	./test_exe > output.log 2>&1 || { cat output.log; rm -f output.log; false; }
	touch test_out