OS := $(shell uname)

BOSATSU_DIR = /Users/oscar/code/bosatsu/.bosatsuc/$(shell ../bosatsuj version -g)

# Platform-specific settings
ifneq ($(wildcard /opt/homebrew/Cellar/bdw-gc),)  # Check if the directory exists
    LATEST_VERSION := $(shell ls -v /opt/homebrew/Cellar/bdw-gc | tail -n 1)
    BOEHM_GC := /opt/homebrew/Cellar/bdw-gc/$(LATEST_VERSION)
endif

ifeq ($(OS), Darwin)
    CFLAGS += -I$(BOEHM_GC)/include
    LIBS += "$(BOEHM_GC)/lib/libgc.a"
else ifeq ($(OS), Linux)
    LIBS += -lgc
endif

LIBS += "$(BOSATSU_DIR)/lib/bosatsu_platform.a"
CFLAGS += "-I$(BOSATSU_DIR)/include"

FLAGS = -flto -O3
//FLAGS = -g

test_exe: output.c
	gcc $(FLAGS) $(CFLAGS) -o test_exe output.c $(LIBS)

test_out: test_exe
	./test_exe > test_out 2>&1 || { cat test_out; rm -f test_out; false; }
	touch test_out