import BazelDepsApi as ___iBazelDepsApi0
import Bosatsu.Predef as ___iPredef1

def ___t0(___bb0):
    return ___iBazelDepsApi0.scala_dep(___bb0[0], ___bb0[1], ___bb0[2])
main = (___iBazelDepsApi0.default_options_with_scala,
    ___iBazelDepsApi0.merge_dep_List(___iPredef1.concat(___iPredef1.map_List((1,
                    ("com.lihaoyi", "sourcecode", "0.1.4"),
                    (1,
                        ("com.monovore", "decline", "1.0.0"),
                        (1,
                            ("org.bykn", "fastparse-cats-core", "0.1.0"),
                            (1,
                                ("org.scala-lang.modules", "scala-xml", "1.0.6"),
                                (1,
                                    ("org.scalacheck", "scalacheck", "1.13.5"),
                                    (1,
                                        ("org.scalactic", "scalactic", "3.0.1"),
                                        (1,
                                            ("org.spire-math", "kind-projector", "0.9.4"),
                                            (1,
                                                ("org.typelevel", "alleycats-core", "2.0.0"),
                                                (1,
                                                    ("org.typelevel", "cats-effect", "2.0.0"),
                                                    (1,
                                                        ("org.typelevel", "paiges-core", "0.3.0"),
                                                        (0,))))))))))),
                ___t0),
            (1,
                ___iBazelDepsApi0.scala_dep_modules("org.scalatest",
                    "scalatest",
                    (1, "", (0,)),
                    "3.0.1",
                    (1, "org.scalactic:scalactic", (0,))),
                (1,
                    ___iBazelDepsApi0.scala_dep_modules("org.typelevel",
                        "cats",
                        (1, "core", (1, "free", (1, "kernel", (1, "macros", (0,))))),
                        "2.0.0",
                        (0,)),
                    (1,
                        ___iBazelDepsApi0.scala_dep_modules("com.lihaoyi",
                            "fastparse",
                            (1, "", (1, "utils", (0,))),
                            "1.0.0",
                            (1, "com.lihaoyi:sourcecode", (0,))),
                        (0,)))))),
    ___iBazelDepsApi0.standard_scala_replacements)